### ISSUE TITLE
Missing LagaDatabase.mdf

### ISSUE THREAD

**Issue by sjh37** [drydenmaker/EF.Reverse.Poco.Generator.Migrations#1]
Can you include the MDF file so I can generate the poco code.

**Comment by drydenmaker** [comment]
It was generated from SQL Server initially.  I will commit the sql scripts.  Thanks for taking a look.  I half suspect it has to do with the text fields, but the fact that the EF6 Designer code works raises the question.

**Comment by sjh37** [comment]
Thanks
