### ISSUE TITLE
Take a look at this code, see if it works for you

### ISSUE THREAD

**Issue by sjh37** [drydenmaker/EF.Reverse.Poco.Generator.Migrations#2]
Download zip file [here](www.hicrest.net/EF.Reverse.Poco.Generator.Migrations-SimonHughes.zip).

**Comment by drydenmaker** [comment]
Can't hit the download.  Are you able to PR?

**Comment by sjh37** [comment]
Sorry, use this link.
www.hicrest.net/EF.Reverse.Poco.Generator.Migrations-SimonHughes.zip

**Comment by drydenmaker** [comment]
So ultimately it just comes down to adding some sort of name to 'MigrationConfigurationFileName' so that it has a migration?

**Comment by sjh37** [comment]
Basically yes. When it sees MigrationConfigurationFileName has a value, it adds the migration configuration, i used a dummy as you already have one, and includes the call to the initialiser as defined in MigrationStrategy.

**Comment by drydenmaker** [comment]
so I put a migration configuration in there to show what I was talking about with the awkward feel of the test.

I was also wondering if this is the proper way to setup data-safe migrations?

**Comment by drydenmaker** [comment]
If you leave the answer over on StackOverflow I will mark it as such.  I really appreciate your help.
